import type { AisupConfig } from './schema.js';

export const CONFIG_DEFAULTS: Omit<AisupConfig, 'accounts'> = {
  runner: {
    command: 'pilot',
    args: [],
    resume_flag: '--resume',
    config_dir_env: 'CLAUDE_CONFIG_DIR',
    remote_control_prefix: null,
  },
  thresholds: {
    soft_pct: 85,
    hard_pct: 95,
    idle_boundary_seconds: 30,
  },
  failover: {
    circuit_breaker_max_failures: 3,
    circuit_breaker_cooldown_seconds: 300,
  },
  skills: {
    tracked: ['/prd', '/spec', '/fix', '/review', '/security-review'],
  },
  monitoring: {
    rate_limit_interval_s: 30,
    health_interval_s: 60,
    recovery_interval_s: 5,
    idle_interval_s: 120,
  },
  session: {
    output_log_max_size_mb: 50,
    output_log_retention_days: 7,
    resume_prompt_mode: 'never',
    tmux_socket: 'aisup',
  },
  recovery: {
    auto_resume_exhausted: true,
    exhausted_poll_interval_s: 60,
    network_error_threshold: 3,
    max_exhausted_retries: 5,
  },
  permissions: {
    enabled: false,
    detection_patterns: [],
    approval_key: 'y',
    denial_key: 'n',
    policy: {
      allowlist: [],
      denylist: [],
      default_action: 'deny',
    },
    slack_routing: false,
    grant_ttl_seconds: 300,
  },
  gates: {
    enabled: false,
    gates: [],
    trigger: 'idle_and_skill',
    idle_delay_seconds: 30,
  },
  slack: {
    enabled: false,
    bot_token_env: 'AISUP_SLACK_BOT_TOKEN',
    app_token_env: 'AISUP_SLACK_APP_TOKEN',
    allowed_user_ids: [],
    relay_output_enabled: false,
    cmd_require_confirmation: true,
    redaction_patterns: [],
  },
  daemon: {
    port: 7394,
    log_max_size_mb: 10,
  },
  statusline: {
    directory: '/tmp/pilot-failover',
    freshness_window_s: 300,
  },
  journal: {
    path: '~/.aisup/journal.jsonl',
  },
  workers: {
    enabled: false,
    workspace_root: null,
    worktree_dir: '.aisup-workers',
    base_ref: 'HEAD',
    max_concurrent: 2,
    retention: {
      keep_merged: false,
      keep_rejected: true,
      max_age_hours: 168,
    },
    security: {
      env_allowlist: ['PATH', 'HOME', 'LANG'],
      boundary_audit: true,
      forbidden_path_globs: [
        '**/.claude/settings.local.json',
        '**/.claude/transcripts/**',
        '**/*.jsonl',
        '**/*.tmux-capture',
        '**/*.pem',
        '**/.env',
        '**/.env.*',
      ],
    },
    adapters: {
      codex: {
        name: 'codex',
        command: 'codex',
        args: [],
        prompt_via: 'arg',
        prompt_arg_flag: null,
        prompt_file_flag: null,
        env_allowlist: ['PATH', 'HOME'],
        timeout_seconds: 1800,
        enabled: false,
      },
      gemini: {
        name: 'gemini',
        command: 'gemini',
        args: [],
        prompt_via: 'arg',
        prompt_arg_flag: null,
        prompt_file_flag: null,
        env_allowlist: ['PATH', 'HOME'],
        timeout_seconds: 1800,
        enabled: false,
      },
      local: {
        name: 'local',
        command: '',
        args: [],
        prompt_via: 'stdin',
        prompt_arg_flag: null,
        prompt_file_flag: null,
        env_allowlist: ['PATH', 'HOME'],
        timeout_seconds: 1800,
        enabled: false,
      },
    },
    routing: {
      default_implementer: 'codex',
      default_reviewer: 'gemini',
      by_task_type: {},
    },
    review: {
      allow_same_model_review: false,
    },
    validation_gates: [],
    validation: {
      allow_no_validation: false,
    },
    merge: {
      require_approval: true,
      apply_check_required: true,
    },
  },
};
